development:
  adapter: postgresql
  database: twitter_development
  username: gocase
  password: lovegocase
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: twitter_test
  username: gocase
  password: lovegocase
  encoding: unicode
  host: localhost
  pool: 5